---
# The name of the playbook or play
- name: Example Playbook
  
  # The hosts on which this playbook will run. 'all' means it will run on all hosts in the inventory.
  hosts: all

  # 'become' indicates whether to use privilege escalation (e.g., sudo) to perform tasks that require elevated permissions.
  become: yes

  # List of tasks to execute on the hosts
  tasks:

    # A task that installs a package
    - name: Install a package
      # The 'apt' module is used for package management on Debian-based systems
      apt:
        # Name of the package to install
        name: vim
        # Ensures that the package is installed (present state)
        state: present
